language: c++
compiler:
  - g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libsfml-dev-2.4.1
before_script:
  - mkdir build

script: make
